spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monta
    username: root
    password: 1171
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://hororok-monta.c76ookck0cc9.us-east-1.rds.amazonaws.com:3306/monta
#    username: admin
#    password: qwer1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
jwt:
  header: Authorization
  secret: aG9yb3Jvay1tb250YS1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWhvcm9yb2stbW9udGEtc3ByaW5nLWJvb3Qtand0LXNlY3JldA==
  token-validity-in-seconds: 604800 # 일주일